spring:
  datasource:
    url: ${DB_url}
    username: ${DB_username}
    password: ${DB_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

server:
  port: 60002


rsa:
  public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAr2FGTai8H3Wmhy7KbaF90An2EdWvtTSqphDyseD8o3tfN5f9kt1qgaxe6uQE19FIpqwDv1ufXnI6zNp/fIB1tWB2WjV7IBlqkPKcYmbPuBSpiFhIynLN0n9yEcDchpKGGnLx0kmpmA5yHgKXZlC0v/9d6VLIsga7T3ZLxxytQDX7IexKnB54otEs+T1ETI7nb+otTax3Qp0e7nEsjQpRDKaY8P3g7yfadPNiEcRuiugpSYP9aACOp4lKSfUS+MaZ3wvOalu02F3RdI4cvVyCbdLpqCS1xFvAJeFubbJ1lG5las2UkN0HOYew2+uegjWKAsQzZ9R/F6ayh4Fhwz1CfwIDAQAB
  private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCvYUZNqLwfdaaHLsptoX3QCfYR1a+1NKqmEPKx4Pyje183l/2S3WqBrF7q5ATX0UimrAO/W59ecjrM2n98gHW1YHZaNXsgGWqQ8pxiZs+4FKmIWEjKcs3Sf3IRwNyGkoYacvHSSamYDnIeApdmULS//13pUsiyBrtPdkvHHK1ANfsh7EqcHnii0Sz5PURMjudv6i1NrHdCnR7ucSyNClEMppjw/eDvJ9p082IRxG6K6ClJg/1oAI6niUpJ9RL4xpnfC85qW7TYXdF0jhy9XIJt0umoJLXEW8Al4W5tsnWUbmVqzZSQ3Qc5h7Db656CNYoCxDNn1H8XprKHgWHDPUJ/AgMBAAECggEATAS3C3xjJqPBbgEbH1ALj7xxm6NrCPluKpNYD0A9YcNdL2TDNgChZNnJPrldXArMGeqfqTdWqgKLeDYRYm7wFpFcW5eo6e36Yh+3J3P2/4x9O6tAyfffPSme0REuxWoHlLlUFll1mIJSdq2a4G+FGV/gXf1THs+KK1RUXlcQxa6ndJCzGY5caYWwpYy9BsxJA+DyGGMH2A5duuPef5Py6TzYvjFwZBoHWDqEurFRBfgxsG3J+1Lt8kxpZFrmS2ytouU4fagHuHvaFNNKQZfb3zplxjxRWIT5KO7C1/FDrfZ+UVVTO+SYugm8JutcYGDfDMInkgs6olj42sKF2qULkQKBgQDtIEuWtx9VAcJBlMC8Zj5rSK9chMZ3fr8QiEHxHPYGVDxyaSDM/bg1aUk0th7caTvOky7BWsuyVgVOt4gyd3+i3NIPE8TcP12Loij5nN1txlWiz6L9XvsAHCaX9+reT1RhJzemYCg0r5/0gG3i4E2UNzRbrKh4Wbd2D290Si935wKBgQC9VtVhTGmh9V9SYw8hcq4sinychZ+tbEUsAoRT5Fimxl4AsIYCT5/TviMNvhLsX66TB+CCXHLXfrmPnveZiJz0nYmNkRuK2QHV8UZ/A1ChHMRvNEPCLOOBk9+XEsPtLY+jEEjK87BEDi+qsDBj9Vg+fPoCLNvCtMgx6yXrXyCtqQKBgDFNN6ocZN1Nwk/UV8ZUE8JGmH9J8+HAboVHbz5sYRKrzO2Uwgcc8YHZZCkbfIsjLhYjL+Nvt05a6DuXmS+0/Mql0t7jo1iPrCluC8rqPHeodwGk3iSD7Pf24mdSWnjiUY7pkn57G6Doqv8w/KfhLwAUAkTVPynWrXhUeT3adsgdAoGBAKKHZHm2P0Lwv5eYQwfCSrMfWeJ+bdhPhX1G19KvxE29IDpVTWO0eA0qPSrxy4qug8vgyh79PvOu65jWq9JWy+zLQqWMN2lT6Nh+2bXz4YW7jP+sjLGlGNJFXnxvdlIldxRRyTq2PsvcpZxOy+syU0Kow2+UlDyqNONs6EsIiKOpAoGADuq+jxTQkwlOPYY8Et1fftKvrbUSxGy3SXnaWzotwNzvoH/yxLqsPnynDSP+dYO4FGVCm8fouZVWM/uVpAPd1k1TG8WfXZwH2pqWATMmROMIPNCMUrkTDJUHNvksgQHjUulEdtvQR7/BUGX2N9phF6N2pC+fTo2SsvVR+qmXSMg=
